"""add proof_text to challenge progress

Revision ID: 94a07b17999b
Revises: 
Create Date: 2026-06-11 11:40:40.154351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a07b17999b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_text', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_progress', schema=None) as batch_op:
        batch_op.drop_column('proof_text')

    # ### end Alembic commands ###
