"""'add_composite_index_to_carbon_entries'

Revision ID: eaca73422883
Revises: 94a07b17999b
Create Date: 2026-06-17 21:18:05.642834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaca73422883'
down_revision = '94a07b17999b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carbon_entries', schema=None) as batch_op:
        batch_op.create_index('idx_carbon_entries_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_carbon_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_carbon_entries_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('challenge_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_image', sa.Text(), nullable=True))
        batch_op.create_index('idx_progress_lookup', ['user_id', 'challenge_id', 'completion_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_progress_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_is_completed'), ['is_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_is_completed'))

    with op.batch_alter_table('challenge_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_progress_user_id'))
        batch_op.drop_index('idx_progress_lookup')
        batch_op.drop_column('proof_image')

    with op.batch_alter_table('carbon_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carbon_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_carbon_entries_created_at'))
        batch_op.drop_index('idx_carbon_entries_user_created')

    # ### end Alembic commands ###
